codecov:
  require_ci_to_pass: yes
  notify:
    wait_for_ci: yes

coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    project:
      default:
        target: 70%
        threshold: 5%
    patch:
      default:
        target: 70%
        threshold: 5%

ignore:
  - "tests/**/*"
  - "setup.py"
  - "docs/**/*"

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false 
